---
- name: configure prefix-lists
  hosts: network
  gather_facts: false

  tasks:

  - name: Merge provided Prefix lists configuration
    cisco.ios.ios_prefix_lists:
      config:
        - afi: ipv6
          prefix_lists:
            - name: test_ipv6
              description: this is ipv6 merge test
              entries:
                - action: deny
                  prefix: 2001:DB8:0:4::/64
                  ge: 80
                  le: 100
                  sequence: 10
      state: merged
    when: ('ios' in ansible_network_os)

  - name: Merge prefix-lists with Arista device config using resource module
    arista.eos.eos_prefix_lists:
      config:
        - afi: "ipv4"
          prefix_lists:
            - name: "v401"
              entries:
                - sequence: 25
                  action: "deny"
                  address: "45.55.4.0/24"
                - sequence: 100
                  action: "permit"
                  address: "11.11.2.0/24"
                  match:
                    masklen: 32
                    operator: "ge"
            - name: "v402"
              entries:
                - action: "deny"
                  address: "10.1.1.0/24"
                  sequence: 10
                  match:
                    masklen: 32
                    operator: "ge"
        - afi: "ipv6"
          prefix_lists:
            - name: "v601"
              entries:
                - sequence: 125
                  action: "deny"
                  address: "5000:1::/64"
    when: ('eos' in ansible_network_os)
