---
- name: configure prefix-lists
  hosts: arista
  gather_facts: false

  tasks:

  - name: Merge prefix-lists with Arista device config using resource module
    arista.eos.eos_prefix_lists:
      config:
        - afi: "ipv4"
          prefix_lists:
            - name: "v401"
              entries:
                - sequence: 25
                  action: "deny"
                  address: "45.55.4.0/24"
                - sequence: 100
                  action: "permit"
                  address: "11.11.2.0/24"
                  match:
                    masklen: 32
                    operator: "ge"
            - name: "v402"
              entries:
                - action: "deny"
                  address: "10.1.1.0/24"
                  sequence: 10
                  match:
                    masklen: 32
                    operator: "ge"
        - afi: "ipv6"
          prefix_lists:
            - name: "v601"
              entries:
                - sequence: 125
                  action: "deny"
                  address: "5000:1::/64"
                  
  - name: Merge Junos prefix lists
    junipernetworks.junos.junos_prefix_lists:
      config:
        - name: Internal
          address_prefixes:
            - 172.16.1.32
            - 172.16.3.32
        - name: Test1
          dynamic_db: true
        - name: Test2
          address_prefixes:
            - 172.16.2.32
            - 172.16.7.32
            - 172.16.9.32
      state: merged
