---
- name: gather network resources information from routers
  hosts: cisco
  gather_facts: false

  tasks:
    - name: gather router facts
      cisco.ios.facts:

    - name: display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
    
    # Collect only the interfaces facts
    - cisco.iosxr.iosxr_facts:
      gather_subset:
      - '!all'
      - '!min'
      gather_network_resources:
      - interfaces
      - ospfv2
