---
- name: gather network resources information from routers
  hosts: cisco
  gather_facts: true

  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
    commands: show version
  
