---
- name: gather network resources information from routers
  hosts: cisco
  gather_facts: true

  tasks:
    - name: gather router facts
      cisco.ios.facts:

    - name: display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
    
    - name: display resources facts
      gather_subset:
      - '!all'
      - '!min'
      gather_network_resources:
      - interfaces
      - prefix_lists
      - opsf
      debug:
        msg: "Prefix-lists is: {{ ansible_prefix_lists }}"
